name: Deploy to Railway


on:
  push:
    branches:
      - nepse-chatbot
  # pull_request:
  #   branches:
  #     - nepse-chatbot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate with Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        run: railway deploy --yes
